steam_games/add_note_on_site/urls.py
from django.urls import include, path
from .views import GameNoteCreateView, GameNoteListView, GameNoteUpdateView, GameNoteDeleteView
from rest_framework import routers
from .views import GameNoteViewSet

app_name = 'add_note_on_site'

router = routers.DefaultRouter()
router.register(r'game-notes', GameNoteViewSet)


urlpatterns = [
    path("api/", include(router.urls)),
    path("add_note/",GameNoteCreateView.as_view(), name="add_note"),
    path("my_notes/",GameNoteListView.as_view(), name="my_notes"),
    path("my_notes/<int:pk>",GameNoteUpdateView.as_view(), name="update"),
    path("my_notes/delete/<int:pk>",GameNoteDeleteView.as_view(), name="delete"),

]

steam_games/my_auth/urls.py
from django.urls import path, reverse_lazy
from .views import (
    LoginView,
    LogoutView,
    RegisterView
)

app_name = 'my_auth'

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name="register")

]

steam_games/steam_games/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from add_note_on_site.views import game_autocomplete

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='add_note_on_site/index.html')),
    path('notes/', include('add_note_on_site.urls')),
    path('auth/', include('my_auth.urls')),
    path('game-autocomplete/', game_autocomplete, name='game-autocomplete'),
    
]

steam_games/add_note_on_site/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from my_auth.models import Profile


class GameNote(models.Model):
    name = models.TextField()
    is_finished = models.BooleanField()
    want_to_play = models.BooleanField()
    score = models.IntegerField(null=True, validators=[MinValueValidator(1), MaxValueValidator(100)])
    hours = models.IntegerField(null=True)
    created_at = models.DateField(auto_now_add=True)
    user_profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='game_notes', null=True)
    # optional_notes = models.TextField(null=True)

    def __str__(self):
        return self.name

steam_games/add_note_on_site/forms.py
from django import forms
from add_note_on_site.models import GameNote


class GameNoteForm(forms.ModelForm):
    
    name = forms.CharField(
        label="Введите название игры*",
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Введите название игры",
                "class": "form-control mb-3",
                'style': 'width: 100%; height: 45px; font-size: 18px;',
                "id": "game-name",
            }
        ),
    )

    is_finished = forms.BooleanField(
        label="Игру уже прошёл!",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input me-2"}),
    )

    want_to_play = forms.BooleanField(
        label="Буду играть или играю сейчас",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input me-2"}),
    )

    score = forms.IntegerField(
        label="Ваша оценка игре до 100",
        required=False,
        widget=forms.NumberInput(attrs={
            'class': 'form-control mb-3',
            'min': 0,
            'max': 100,
            'style': 'width: 30%; height: 40px; font-size: 18px;'
        }),
        min_value=0,
        max_value=100
    )

    hours = forms.IntegerField(
        label="Сколько часов ушло на прохождение?",
        required=False,
        widget=forms.NumberInput(attrs={
            'class': 'form-control mb-3',
            'style': 'width: 30%; height: 40px; font-size: 18px;'
        }),
        min_value=0,
    )

    # optional_notes = forms.CharField(
    #     label="Дополнительные заметки",
    #     required=False,
    #     widget=forms.Textarea(
    #         attrs={
    #             "placeholder": "Введите ваши заметки здесь",
    #             "class": "form-control mb-3",
    #             'style': 'height: 150px; width: 100%; font-size: 16px; resize: vertical;'
    #         }
    #     )
    # )

    class Meta:
        model = GameNote
        fields = ["name", "is_finished", "want_to_play", "score", "hours"]

steam_games/add_note_on_site/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from rest_framework import permissions
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from add_note_on_site.models import GameNote
from add_note_on_site.forms import GameNoteForm
from database.models import Game
from my_auth.models import Profile
from .models import GameNote
from .serializers import GameNoteSerializer


class GameNoteViewSet(ModelViewSet):
    queryset = GameNote.objects.all().order_by("-created_at")
    serializer_class = GameNoteSerializer
    filter_backends = [
        SearchFilter,
        OrderingFilter,
    ]
    search_fields = ["name", "score"]
    ordering_fields = ["name", "score", "hours", "created_at"]
    permission_classes = [permissions.IsAdminUser]


class GameNoteCreateView(CreateView):
    model = GameNote
    template_name = "add_note_on_site/add.html"
    success_url = reverse_lazy("add_note_on_site:my_notes")
    form_class = GameNoteForm

    def form_valid(self, form):
        # Устанавливаем профиль текущего пользователя в поле `profile`
        form.instance.user_profile = Profile.objects.get(user=self.request.user)
        return super().form_valid(form)


class GameNoteUpdateView(UpdateView):
    model = GameNote
    template_name = "add_note_on_site/update.html"
    success_url = reverse_lazy("add_note_on_site:my_notes")
    form_class = GameNoteForm


class GameNoteDeleteView(DeleteView):
    model = GameNote
    success_url = reverse_lazy("add_note_on_site:my_notes")


class GameNoteListView(ListView):
    model = GameNote
    paginate_by = 10
    template_name = "add_note_on_site/my_notes.html"

    def get_queryset(self):
        profile = Profile.objects.get(user=self.request.user)
        # Фильтруем по Profile, а не по User
        queryset = GameNote.objects.filter(user_profile=profile).select_related('user_profile').order_by("-id")
        return queryset


def game_autocomplete(request):
    if 'term' in request.GET:
        query = request.GET['term']
        games = Game.objects.filter(name__icontains=query)[:20]  # Ограничиваем до 10 результатов
        results = [{'id': game.id, 'label': game.name} for game in games]
        return JsonResponse(results, safe=False)
    return JsonResponse([], safe=False)

steam_games/add_note_on_site/templates/add_note_on_site/add.html
{% extends "add_note_on_site/my_notes.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Game Form</title>
    <!-- Подключение jQuery и jQuery UI для автокомплита -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> <!-- Подключение вашего CSS файла -->
</head>

{% block header %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal text-body-emphasis" style="margin-bottom: 60px;"><a href="/notes/my_notes" style="color: #ffffff;">Мой игровой блокнот</a></h1>
    <p class="fs-5 text-body-secondary" style="color: #ffffff;">Посмотрите на список Ваших игр: какие-то из них вы уже прошли, а какие-то только собираетесь!
         Что будем делать сегодня?</p>
  </div>
{% endblock %}

{% block content %}
<body>
    <div class="container mt-5">
        <div class="shadow-sm rounded mb-3 bg-white" style="padding: 1rem; max-width: 800px; margin: auto;">

            <h2 class="text-center mb-4">Добавить запись о игре</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary w-100" style="margin-top: 70px;">Сохранить</button>
            </form>
        </div>
    </div>
</body>
<style>
    body {
        background-image: url("{% static 'img/1.jpg' %}");
        background-size: cover;
        background-position: center;
    }
    form {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
    }
    .form-group {
        margin-bottom: 15px;
    }
    .form-control {
        padding: 10px;
        font-size: 16px;
        border-radius: 5px;
    }
    button {
        padding: 10px;
        font-size: 16px;
        font-weight: bold;
        background-color: #007BFF;
        color: white;
        border: none;
        border-radius: 5px;
    }
    button:hover {
        background-color: #0056b3;
    }
    .text-center {
        text-align: center;
    }
    
</style>
<!-- Подключение jQuery (если ещё не подключен) -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Подключение jQuery UI для автозаполнения -->
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script type="text/javascript">
    $(document).ready(function() {
        // Инициализация автозаполнения
        $('#game-name').autocomplete({
            source: function(request, response) {
                $.ajax({
                    url: '{% url "game-autocomplete" %}',
                    data: {
                        'term': request.term  // Передаём введённый текст
                    },
                    success: function(data) {
                        response(data);  // Ответ от сервера
                    }
                });
            },
            minLength: 2,  // Минимальное количество символов для начала поиска
            select: function(event, ui) {
                // Можно сделать что-то, если пользователь выбрал игру из списка
                $('#game-name').val(ui.item.label);  // Заполняем поле выбранным названием игры
            }
        });
    });
</script>

{% endblock %}
</html>

steam_games/add_note_on_site/templates/add_note_on_site/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
  <title>Игровой блокнот</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    body {
      display: flex;
      align-items: center;
      justify-content: center;
      height: 100vh;
      color: white;
      text-align: center; 
      background-image: url("{% static 'img/1.jpg' %}");
      background-size: cover;
      background-position: center;
    }
    .cover-container {
      max-width: 42em;
    }
    .btn {
      margin-top: 20px;
    }
  </style>
      <link href="{% static  'css/cover.css' %}" rel="stylesheet">
</head>
<body>
  <div class="cover-container">
    <header class="mb-auto">
      <div>
        <!-- <h3 class="float-md-start mb-0">Cover</h3>
        <nav class="nav nav-masthead justify-content-center float-md-end">
          <a class="nav-link active" href="#">Home</a>
          <a class="nav-link" href="#">Features</a>
          <a class="nav-link" href="#">Contact</a> -->
        </nav>
      </div>
    </header>
  <main class="px-3">
    <h1>Привет! Добро пожаловать в ваш личный игровой блокнот.</h1>
    <p class="lead">Войдите или зарегистрируйтесь, чтобы получить доступ к своему профилю, а также добавлять и просматривать записи о прохождении игр.</p>
    <div class="d-flex justify-content-center">
        <p class="lead me-2">
            <a href="/auth/login" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Войти</a>
        </p>
        <p class="lead">
            <a href="/auth/register" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Присоединиться</a>
        </p>
    </div>
</main>
    <footer class="mt-auto text-white-50">
      <!-- <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a> by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p> -->
    </footer>
  </div>
</body>
</html>

steam_games/add_note_on_site/templates/add_note_on_site/update.html
{% extends "add_note_on_site/my_notes.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Game Form</title>
    <!-- Подключение jQuery и jQuery UI для автокомплита -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> <!-- Подключение вашего CSS файла -->
</head>

{% block header %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal text-body-emphasis" style="margin-bottom: 60px;"><a href="/notes/my_notes" style="color: #ffffff;">Мой игровой блокнот</a></h1>
    <p class="fs-5 text-body-secondary" style="color: #ffffff;">Посмотрите на список Ваших игр: какие-то из них вы уже прошли, а какие-то только собираетесь!
        Что будем делать сегодня?</p></div>
{% endblock %}

{% block content %}
<body>
    <div class="container mt-5">
        <div class="shadow-sm rounded mb-3 bg-white" style="padding: 1rem; max-width: 800px; margin: auto;">
            <h2 class="text-center mb-4">Отредактировать запись</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <br>
                <div class="d-flex justify-content-start">
                    <button type="submit" class="btn btn-primary" style="margin-right: 10px;">Обновить запись</button>
                </form>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                        Удалить запись
                    </button>
                    
  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Удаление записи</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Вы уверены, что хотите удалить запись?
        </div>
        <div class="modal-footer">

          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Назад</button>
          <form action="{% url 'add_note_on_site:delete' object.pk %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Да</button>
        </form>
        </div>
      </div>
    </div>
  </div>

</div>
</div>
</div>
</body>
<style>
    body {
        background-image: url("{% static 'img/1.jpg' %}");
        background-size: cover;
        background-position: center;
    }
    form {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
    }
    .form-group {
        margin-bottom: 15px;
    }
    .form-control {
        padding: 10px;
        font-size: 16px;
        border-radius: 5px;
    }
    button {
        padding: 10px;
        font-size: 16px;
        font-weight: bold;
        background-color: #007BFF;
        color: white;
        border: none;
        border-radius: 5px;
    }
    button:hover {
        background-color: #0056b3;
    }
    .text-center {
        text-align: center;
    }
    
</style>
<!-- Подключение jQuery (если ещё не подключен) -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Подключение jQuery UI для автозаполнения -->
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script type="text/javascript">
    $(document).ready(function() {
        // Инициализация автозаполнения
        $('#game-name').autocomplete({
            source: function(request, response) {
                $.ajax({
                    url: '{% url "game-autocomplete" %}',
                    data: {
                        'term': request.term  // Передаём введённый текст
                    },
                    success: function(data) {
                        response(data);  // Ответ от сервера
                    }
                });
            },
            minLength: 2,  // Минимальное количество символов для начала поиска
            select: function(event, ui) {
                // Можно сделать что-то, если пользователь выбрал игру из списка
                $('#game-name').val(ui.item.label);  // Заполняем поле выбранным названием игры
            }
        });
    });
</script>



{% endblock %}


</html>